### ISSUE TITLE
Requires dev testthat?

### ISSUE THREAD

**Issue by hadley** [kevinushey/sourcetools#1]
When building, I get:

```
test-Tokenizer.cpp:1:10: fatal error: 'tests/testthat.h' file not found
#include <tests/testthat.h>
```

**Comment by kevinushey** [comment]
Indeed it requires the dev `testthat`. (I vaguely recall the latest `devtools` has a way of declaring that?)

**Comment by hadley** [comment]
You should put a version req in the `LinkingTo` and add a remotes (see the devtools blog post before last)

**Comment by kevinushey** [comment]
Thanks! Should be good to go with https://github.com/kevinushey/sourcetools/commit/456e008883622254fa27abdbdcbf367d57bc512d.
